server:
  port:
    8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8092
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8093
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: http://localhost:8091
          predicates:
            - Path=/products/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm