server:
  port:
    8093

spring:
  application:
    name:
      orderservice
  datasource:
    url:
      jdbc:mysql://localhost:3306/trainingdb?useSSL=false
    username:
      root
    password:
      root
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      properties:
        spring.json.trusted.packages: "*"
      group-id: order-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: order-created:com.rahul.orderservice.dto.OrderCreatedEvent
