server:
  port: 8094

spring:
  application:
    name: notificationservice
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
